# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_16 ];
      }
      ''
        # workaround https://codeberg.org/ziglang/zig/issues/31866
        # https://github.com/Cloudef/zig2nix/issues/54
        mkdir "$TMPDIR/src" "$TMPDIR/cache" "$TMPDIR/cache/tmp"
        touch "$TMPDIR/src/build.zig"
        hash="$(cd "$TMPDIR/src" && zig fetch --global-cache-dir "$TMPDIR/cache" ${artifact})"
        mkdir "$out"
        tar zxvf "$TMPDIR/cache/p/$hash.tar.gz" --directory "$out/" --strip-components=1
      '';

  fetchZig =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      artifact =
        if unpack then
          fetchzip {
            inherit url hash;
            nativeBuildInputs = [ zstd ];
          }
        else
          fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash unpack;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash unpack;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
  # The packages, as real directories holding symlinked files, rather than as
  # a farm of symlinked directories.
  #
  # Zig runs a dependency's own build steps with the working directory set to
  # that dependency, and points at the program to run with a path counted in
  # directories up from there. Through a symlink the two disagree: Zig counts
  # from `<farm>/<package>/`, four directories below the root, while the kernel
  # resolves the working directory to `/nix/store/<hash>`, which is three, so
  # the path lands one short of where the program is.
  #
  # It works anyway when the build directory is `/build`, because the sum then
  # overshoots into the root and going above the root stays there. It fails
  # when the build directory is under `/nix/var/nix/builds`, which is where Nix
  # puts it when the sandbox is off. Real directories make the two depths
  # agree, so it works either way.
  #
  # The files have to be real as well, which is the expensive part and cannot
  # be avoided. `--symbolic-link` would leave them pointing into each
  # dependency's own store path, so that the farm is a few megabytes rather
  # than a second copy of every dependency -- but Zig's
  # `installHeadersDirectory` walks the directory and copies only the entries
  # whose kind is `.file`. Symlinked headers are skipped without a word, and
  # the first thing to include one fails with `'dcimgui.h' not found`.
  #
  # `--link` is not the way out. A hard link into a Nix output is a file the
  # builder did not create: inside the Linux sandbox the store is a separate
  # mount and `link` fails with `Invalid cross-device link`, while on Darwin it
  # succeeds and leaves root-owned files in the output, which Nix refuses while
  # canonicalising with `invalid ownership on file`.
  #
  # So it is a real copy, with `--reflink=auto` to share the blocks on a
  # filesystem that can. `nix store optimise` recovers the duplication after
  # the fact, hard-linking identical files across the store, which is the
  # store's own business to do and not a build's.
  copyFarm =
    farm: entries: pathDependencyPackages:
    runCommandLocal farm
      {
        # The packages whose own manifest declares a dependency by `.path`.
        # Zig 0.16.0 cannot build these through `zig build --system`: it spins
        # in userspace forever, because a `.path` dependency's hash is computed
        # against the system package directory during the fetch and against the
        # real global cache afterwards, and in that mode the two disagree. A
        # package that wants `--system` copies each of these into its build
        # root and passes `--fork=`; see the README.
        passthru = { inherit pathDependencyPackages; };
      }
      ''
        mkdir -p "$out"
        cp --recursive --reflink=auto --dereference --no-preserve=mode \
          ${linkFarm farm entries}/. "$out/"
      '';
in
copyFarm name
  [
    {
      name = "riff-0.1.0-HAfI3rPCAADDnynVeckIf35oQu3Syx2BJ6qt9v-UTF4y";
      path = fetchZigArtifact {
        name = "riff";
        url = "https://git.jcollie.dev/jeff/zig-riff/archive/b8e61dc1f90239c6ef9cf1185d5993ca87166e89.tar.gz";
        hash = "sha256-1lPXZWq86AARgjHoGF2icuPEpJOdtnox69EJUXErz5c=";
        unpack = true;
      };
    }
    {
      name = "uri-0.1.0-yCrwNNH2EwAHUOoMVFq21bN9Oc84QFSzmPaa6xPh6koO";
      path = fetchZigArtifact {
        name = "uri";
        url = "git+https://git.jcollie.dev/jeff/zig-uri.git#b51701b260f07620b9bf953fc19c902115eac25e";
        hash = "sha256-TlPE0XeSScVocHAqC4bL4o3m7vnR6wEiwkp7clcK9Pc=";
        unpack = true;
      };
    }
    {
      name = "uucode-0.2.0-ZZjBPh-6VADBlunHbwABTPng0DH6uJqd4CvvtjZ19tny";
      path = fetchZigArtifact {
        name = "uucode";
        url = "git+https://github.com/jacobsandlund/uucode#61e54266895f833b307de81a0e3038cf1f1bebd4";
        hash = "sha256-6Riz1CowKgQr70YAcfozHETUqfOR4gYIwUE5txjX70o=";
        unpack = true;
      };
    }
    {
      name = "vp8-0.0.0-8XCztL3qEwCExhrnicHiP0F-Gw8ZRGJ2kVBztgd5dUDp";
      path = fetchZigArtifact {
        name = "vp8";
        url = "https://git.jcollie.dev/jeff/zig-vp8/archive/2b71a352f930f4fa3fc3ba4bbfad53d9acfd37b1.tar.gz";
        hash = "sha256-kSmtmSVZ57BN4CPXdLx2SxCc3OtIuhsXWojD3pnxZnM=";
        unpack = true;
      };
    }
    {
      name = "z2d-0.12.2-pre-j5P_HnUtEgB-WFJ_HPagXmB5wIgULczoSsuw2GNoWQUh";
      path = fetchZigArtifact {
        name = "z2d";
        url = "git+https://git.jcollie.dev/jeff/z2d.git#c016785e3c98f289b11041deb0e60fd0e3103b7f";
        hash = "sha256-0ymKni+/eVe7CwwYRn8hTIDFkfGExQ8BU66P85E3diM=";
        unpack = true;
      };
    }
    {
      name = "z2dimg-0.0.0-N7PaCfgDJQDuLSbcHztfA2lTkEttYcStz49aJ9G-lVr0";
      path = fetchZigArtifact {
        name = "z2dimg";
        url = "git+https://git.jcollie.dev/jeff/z2dimg.git#4af70f61b5c4f7e64602ae3f118c742b09eac866";
        hash = "sha256-W1O7d8oH9o/cQD4P3675hsIA8sItIdfcpy7huT8n0tI=";
        unpack = true;
      };
    }
    {
      name = "z46-0.1.0-_AxhwBHeAwDelVOsDdnw7Rg1ZzCY2uH99YdFQknXdy1J";
      path = fetchZigArtifact {
        name = "z46";
        url = "git+https://git.jcollie.dev/jeff/z46.git#52bc1256116cde4b3e7480d8664da09e5901490a";
        hash = "sha256-U2dGmTMhQI+Yc0Zw9K9rGq1vRSqqTOxI51zxbtiI1Bk=";
        unpack = true;
      };
    }
    {
      name = "zig_css-0.0.0-d530kFLbGgAN4NqKWIX58MC_Mq2QNhfS0ej8r9O_Ftz6";
      path = fetchZigArtifact {
        name = "zig_css";
        url = "git+https://git.jcollie.dev/jeff/zig-css.git#e24444690930931bfec79c4b4efad84e141b8a10";
        hash = "sha256-AmyQbS6knMVIyY6AIM+HJ/nDUPMnr4kBhYhfME4l/+E=";
        unpack = true;
      };
    }
    {
      name = "ztree-0.0.0-Rb9y2UksAwAIl9qdJcWF_hQJ4OByzMagmRh0rxr14Oel";
      path = fetchZigArtifact {
        name = "ztree";
        url = "git+https://git.jcollie.dev/jeff/ztree.git#21a82ffda399367767663b0432bb716d2b620f25";
        hash = "sha256-fvo7u3MwI9BUxtREpRxBX/vPO5UIcClXALaXpKjBkIc=";
        unpack = true;
      };
    }
    {
      name = "zxml-0.0.0-JUQ_3ZzFAwBbkY9YvELURU5yFM7cLH59_W9TJaQy7Tvn";
      path = fetchZigArtifact {
        name = "zxml";
        url = "git+https://git.jcollie.dev/jeff/zxml.git#cfbda2e23d78d55ce0e4b61e8ce8f1aee64a57f4";
        hash = "sha256-918KBARpUtPjVTx+LhpWEVHemUJ6Sp0Orijyp0qMZds=";
        unpack = true;
      };
    }
  ]
  [
  ]
