# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_17,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}:
let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit =
    args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    "css-0.3.0-d530kC4oLwAynd0fs6-ZE0M3xkpVE8tEm7hEAha2_qKu" = fetchZigGit {
      name = "css";
      url = "https://git.jcollie.dev/jeff/zig-css.git";
      rev = "fe0955523b6c47b159ffeac31bd859a91d7b2a23";
      hash = "sha256-I9OXy8Npm0H6hp85We8csaW+PSeVHAoMZ9RRS+yLjSs=";
    };
    "riff-0.3.0-HAfI3hvpAAC0x2BglCLXC8KbAh-2QsqaM7iGWlOdcji3" = fetchzip {
      name = "riff";
      url = "https://git.jcollie.dev/jeff/zig-riff/archive/95720d487115c285f5b890e5788499f3931a4d26.tar.gz";
      hash = "sha256-zIhM3MRgivvegHV+PCPWofjb6H9UxvhAnKQl/60cZGI=";
    };
    "uri-0.4.0-yCrwNG9RFABqcGa05zp-QRUjfajbARn7a9KoY6N6A1v_" = fetchZigGit {
      name = "uri";
      url = "https://git.jcollie.dev/jeff/zig-uri.git";
      rev = "0c174b5afc0b8c1793f4b02de58d25f4b768f102";
      hash = "sha256-YFO1GCcoJB/QLi14FD7+6jNET4SX06etOt6ZwrMcDnY=";
    };
    "uucode-0.2.0-ZZjBPm6FVgBcY-79AHV8ckQj86z0JwOyVyj89VeZrEiv" = fetchZigGit {
      name = "uucode";
      url = "https://github.com/jacobsandlund/uucode";
      rev = "1fb73433bba5d93366c57f23ff2e9d7939746500";
      hash = "sha256-fZTYVFN0N10R0Ty+3tpMkTLqEBq4tTpkBK6G1m6VgmY=";
    };
    "vp8-0.2.0-8XCztDfrEwDYcNhNK6Xm6HNRvQNcchYp6gdlx1dtnAFZ" = fetchzip {
      name = "vp8";
      url = "https://git.jcollie.dev/jeff/zig-vp8/archive/940c92375d7b841a03aa76f5223480834ac03a8f.tar.gz";
      hash = "sha256-pYFG+pqNB3hnSokZAWD4uLEzUxVZR9vaB5WAZOt4CnY=";
    };
    "z2d-0.13.0-j5P_HhoOEwDhf6BtdL-qSncLzYopF4BdDuYtVrl9x_oU" = fetchZigGit {
      name = "z2d";
      url = "https://git.jcollie.dev/jeff/z2d.git";
      rev = "95e6d0dd70d8161f40cd6600a26520c5719b30b5";
      hash = "sha256-wCk4pBNqmaOZLLS9RXh6jW2pFXiAj9TcLBz8YwFuAyk=";
    };
    "z2dimg-0.2.0-N7PaCVAXJADB50Lgp1Fw3phtyQDk6tM3tSHQErraNKOI" = fetchZigGit {
      name = "z2dimg";
      url = "https://git.jcollie.dev/jeff/z2dimg.git";
      rev = "f6037e4b8a65258ac06398082f91fd595f1be109";
      hash = "sha256-FHeHS+b/lUNCaVS/sbA4nbVZzjZB8nGlCGxyVxsMKBc=";
    };
    "z46-0.2.0-_AxhwAXTCQDzvmmh5CP6zrvAk03GpkQz_fdYpbc53DND" = fetchZigGit {
      name = "z46";
      url = "https://git.jcollie.dev/jeff/z46.git";
      rev = "cde52f655fa3a099c016c042c080f8112330f682";
      hash = "sha256-RPKBTbLZ7bIJXb7g5CBytRXGPkT8Tn8dhiavVpz27Tw=";
    };
    "zig_charset-0.2.0-vwxVhZJ4IACGQafWULuP6AIbS9i4O2pl9OOqXIgliUAX" = fetchZigGit {
      name = "zig_charset";
      url = "https://git.jcollie.dev/jeff/zig-charset.git";
      rev = "591ec3da0819d880b539788ede026bfe4a94c9b3";
      hash = "sha256-kwayanmto0vpH3Cgc8FiotgDmW0PYVioiwkaJc2+qXA=";
    };
    "ztree-0.2.0-Rb9y2YsvAwDe_5M0s33sBst4E6CnPW65wP614UbtTdxa" = fetchZigGit {
      name = "ztree";
      url = "https://git.jcollie.dev/jeff/ztree.git";
      rev = "a48ee058ff0b0e9a758573a1c8a0fcbcf62ef2cf";
      hash = "sha256-rHqtnK37VInUVYYi1VuVil5iA1vghG7e47v4OP5Y3DY=";
    };
    "zxml-0.2.0-JUQ_3VWSBACHDuQEBRk261c8VU2k49kO5Cf4pIeJhzEo" = fetchZigGit {
      name = "zxml";
      url = "https://git.jcollie.dev/jeff/zxml.git";
      rev = "5ed321016b104cbfc8f6ea24edf96bf5be4a40a4";
      hash = "sha256-Cg81TK9KfyOtp1S8x+zp8idjhAY/BbKfpiLwOaEvAHs=";
    };
    "zxml-0.2.0-JUQ_3VnJAwDYZssSsJKNSVZZd02dliNj2N9LJwBfadsp" = fetchZigGit {
      name = "zxml";
      url = "https://git.jcollie.dev/jeff/zxml.git";
      rev = "956b354864b3b50347d921eef27419529850346a";
      hash = "sha256-efHpkvtabJW5mbvOOH/yosLEb50Rglj9azaYWBoG2NA=";
    };
  };

  # The packages whose own manifest declares a dependency by `.path`, which
  # Zig 0.16.0 cannot build through `zig build --system`. Listed here too so
  # that every version's expression offers the same things; see the README.
  pathDependencyPackages = [
  ];
in
# One directory holding every package the way Zig unpacks it -- filtered by
# its manifest's `.paths` and checked against its hash -- which is what
# `zig build --system` wants.
#
# They have to be real directories holding real files, not links into each
# package's own store path. Zig runs a dependency's build steps from inside
# it and counts its way back out through `..`, which lands in the wrong place
# when the directory is a symlink; and `installHeadersDirectory` copies only
# what the directory walk calls a file, so symlinked headers are skipped
# without a word. Building them all in one derivation gives real files from
# the start, without a second copy of everything.
runCommandLocal name
  {
    nativeBuildInputs = [ zig_0_17 ];
    passthru = { inherit pathDependencyPackages; };
  }
  ''
    mkdir "$out"

    # Zig 0.17 runs `zig fetch` in a build runner it compiles into the global
    # cache the first time, which takes a minute or more. Every package shares
    # one cache, then, and it is compiled once here before they are fetched
    # several at a time, rather than by each of them at once.
    export ZIG_GLOBAL_CACHE_DIR="$TMPDIR/cache"
    mkdir -p "$ZIG_GLOBAL_CACHE_DIR"
    zig fetch --help >/dev/null

    # Without `--save`, which wants a project to save into, Zig 0.17 unpacks
    # nothing where it can be found: what it keeps is `p/<hash>.tar.gz` in
    # the global cache, the package filtered by its manifest's `.paths` under
    # a single directory named by its hash. Unpacking that gives the
    # directory `zig build --system` wants.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work"

      local hash
      if ! hash="$(cd "$work" && zig fetch "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      tar -xzf "$ZIG_GLOBAL_CACHE_DIR/p/$1.tar.gz" -C "$out"
      rm -f "$ZIG_GLOBAL_CACHE_DIR/p/$1.tar.gz"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    # `-r` because otherwise xargs runs `unpack` once, with no arguments, when
    # there are no packages at all, and the build fails.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -r -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
